### ISSUE TITLE
test-data is mounted on / but it is not a shared mount

### ISSUE THREAD

**Issue by simon-cj** [fatalc/etc#1]
你好!
请教一下deployment.yaml 中 internal-registry.ghostcloud.cn/library/f3fs:v1.85镜像无法拉取，可以用哪儿可以拉？

用源代码编译的镜像，部署时提示错误：
Warning  Failed            0s (x2 over 1s)     kubelet, kube-master-1  Error: failed to start container "s3f3": Error response from daemon: linux mounts: path /var/lib/kubelet/pods/0e627e60-15a2-11ea-a8ca-fa920233d4fe/volumes/kubernetes.io~empty-dir/test-data is mounted on / but it is not a shared mount.

如果去掉deployment.yaml当中的`mountPropagation: Bidirectional`, s3f3 可以正常运行，但是nginx容器没有正常挂载， s3f3容器有挂载。

k8s版本：1.12
望指导

**Comment by fatalc** [comment]
在这里 https://github.com/fatalc/etc/blob/master/s3fs/s3fs/README.md

**Comment by cnfatal** [comment]
https://github.com/fatalc/etc/blob/f15926e64119ba3eeccfeeb0eaf4d5262c5fa739/s3fs/deployment.yaml#L44 更新了镜像地址

**Comment by simon-cj** [comment]
OK，非常感谢
